### ISSUE TITLE
Avaliação Geral do Projeto

### ISSUE THREAD

**Issue by wylliams** [MurilloTande/E-Acad#10]
Adicionar a EAP.
Criar hierarquia de pacotes. 
Requisitos - adicionar o template (tabela).
Projeto com boa hierarquia de pacotes (MVC). Model, view controller. 
Fachada e interface.
Só um membro com commits no repositório.

**Comment by matheusllima19** [comment]
Template de requisitos adicionado. 
EAP adicionada.

**Comment by MurilloTande** [comment]
Hierarquia de pacotes pronta e commit feito.

**Comment by hugoc09** [comment]
Todas as solicitações foram realizadas.
