### ISSUE TITLE
Diagrama de Caso de Uso

### ISSUE THREAD

**Issue by wylliams** [MurilloTande/E-Acad#8]
Informar os outros atores.
Modificar as nomenclaturas dos Casos de Uso (Ex: "Gerenciar contato").

**Comment by hugoc09** [comment]
Professor, nesse caso, estamos querendo mudar a ideia inicial. Seguinte: Qualquer pessoa que quiser criar um evento ou participar de um evento, deverá possuir um registro no nosso sistema, ou seja, possuir um cadastro. Então só teremos um autor. O que o senhor acha disso?
Qualquer coisa conversaremos e explicaremos amanhã na aula.
Em relação a nomenclatura será modificada, assim que fecharmos a modificação que citei acima.

**Comment by matheusllima19** [comment]
https://github.com/MurilloTande/E-Acad/wiki/Diagrama-de-Casos-de-Uso

Feito!!
