### ISSUE TITLE
Diagrama de classes

### ISSUE THREAD

**Issue by wylliams** [MurilloTande/E-Acad#9]
Implementar a abordagem em camadas (MVC).
[RF04] Cadastro de Usuário - Sistema rodando.
Sistema com ótima padronização, utilizando fachada, interface, DAO e controller. 
Tratamentos. 
Commits realizados por u membro do time.
Projeto e-cad.

**Comment by MurilloTande** [comment]
Professor, o sistema está em camadas  e o cadastro de Usuário está rodando.
isso é uma observação?

**Comment by wylliams** [comment]
Implementar em camadas no Diagrama de Classes.

**Comment by hugoc09** [comment]
Professor, isso já tá sendo solicitado na Inssue 10 - "Criar hierarquia de pacotes"
